
attach(data)
model1 <- glm(C~ID*L*S, poisson)
model2 <- update(model1, ~.- ID:L:S)
anova(model1, model2, test="Chi")
model3 <- update(model2, ~.- L:S)
model4 <- update(model2, ~.- ID:S)
model5 <- update(model2, ~.- ID:L)
anova(model2, model3, test="Chi")
anova(model2, model4, test="Chi")
anova(model2, model5, test="Chi")
model6 <- update(model3, ~.- ID:S)
model7 <- update(model6, ~.- ID)
model8 <- update(model6, ~.- L)
model9 <- update(model6, ~.- S)